import { expect, test, type Page } from '@playwright/test';
const base = process.env.VITE_BASE_PATH || '/';
async function lobby(page: Page, url = './') {
  await page.goto(url);
  await expect(page.getByRole('button', { name: 'Let’s run', exact: false })).toBeEnabled({ timeout: 20000 });
  await expect(page.locator('.game-error')).toHaveCount(0);
}
test('desktop lobby, character selection, settings, help and records work', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await lobby(page);
  await expect(page.getByRole('heading', { name: 'Good day for a great leap.' })).toBeVisible();
  await page.locator('.runner-card').nth(1).click();
  await expect(page.locator('.runner-card').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.scene-caption')).toContainText('Meet Dash');
  await page.getByRole('button', { name: 'The crew', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.locator('.gallery-card').nth(2).click();
  await page.getByRole('button', { name: 'Looking good' }).click();
  await expect(page.locator('.runner-card').nth(2)).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.getByRole('switch', { name: 'Chill mode' }).click();
  await page.getByLabel('Graphics quality').selectOption('low');
  await page.getByRole('button', { name: 'All set' }).click();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Let’s run', exact: false })).toBeEnabled();
  await expect(page.locator('.runner-card').nth(2)).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'How to play', exact: false }).click();
  await expect(page.getByRole('heading', { name: 'The road is lava.' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Your run records' }).click();
  await expect(page.locator('.records-grid')).toContainText('Best distance');
  await page.keyboard.press('Escape');
  await page.screenshot({ path: '/tmp/rooftop-final-desktop.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('keyboard jump clears a gap, pause freezes play, road fall ends the run, restart works', async ({ page }) => {
  await lobby(page);
  await page.getByRole('button', { name: 'Let’s run', exact: false }).click();
  await expect(page.locator('.game-stage')).toBeVisible();
  await expect(page.locator('.jump-now')).toBeVisible({ timeout: 15000 });
  await page.keyboard.press('Space');
  await expect(page.locator('.jump-prompt')).toContainText('Aim for the next roof');
  await expect(page.locator('.score-pill strong')).not.toHaveText('0m');
  await expect.poll(async () => Number((await page.locator('.score-pill strong').innerText()).replace('m', '')), { timeout: 20000 }).toBeGreaterThan(20);
  await page.getByRole('button', { name: 'Pause game' }).click();
  await expect(page.getByRole('heading', { name: 'World on pause.' })).toBeVisible();
  const distance = await page.locator('.score-pill strong').innerText();
  await page.waitForTimeout(500);
  await expect(page.locator('.score-pill strong')).toHaveText(distance);
  await page.getByRole('button', { name: 'Keep running' }).click();
  await expect(page.getByRole('heading', { name: /Look at you go.|One more leap\?/ })).toBeVisible({ timeout: 20000 });
  await expect(page.locator('.result-stats')).toContainText('roofs');
  await page.keyboard.press('KeyR');
  await expect(page.locator('.game-overlay')).toHaveCount(0);
  await expect(page.locator('.score-pill strong')).toHaveText(/^[0-9]m$/);
  await page.getByRole('button', { name: 'Pause game' }).click();
  await page.getByRole('button', { name: 'Back to the lobby' }).click();
  await expect(page.locator('.game-stage')).toHaveCount(0);
});
test('Android-size touch controls and portrait / landscape layouts work', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
  const page = await context.newPage(); const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await lobby(page, `http://localhost:5173${base}`);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '/tmp/rooftop-final-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Let’s run', exact: false }).tap();
  await page.getByRole('button', { name: 'Jump', exact: true }).tap();
  await expect(page.locator('.jump-prompt')).toContainText('Aim for the next roof');
  await page.getByRole('button', { name: 'Pause game' }).tap();
  await expect(page.getByRole('heading', { name: 'World on pause.' })).toBeVisible();
  await page.setViewportSize({ width: 852, height: 393 });
  await page.screenshot({ path: '/tmp/rooftop-landscape.png' });
  await expect(page.getByRole('button', { name: 'Keep running' })).toBeInViewport();
  await page.getByRole('button', { name: 'Start a new run' }).tap();
  await expect(page.getByRole('button', { name: 'Move left', exact: true })).toBeInViewport();
  await expect(page.getByRole('button', { name: 'Jump', exact: true })).toBeInViewport();
  await page.screenshot({ path: '/tmp/rooftop-mobile-game.png' });
  expect(errors).toEqual([]); await context.close();
});
test('production app is cached and remains playable offline', async ({ browser }) => {
  const context = await browser.newContext(); const page = await context.newPage();
  await lobby(page, `http://localhost:4173${base}`);
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true);
  expect(await page.evaluate(() => new URL(navigator.serviceWorker.controller!.scriptURL).pathname)).toBe(`${base}sw.js`);
  const manifest = await (await page.request.get(`http://localhost:4173${base}manifest.webmanifest`)).json();
  expect(manifest.start_url).toBe('./'); expect(manifest.scope).toBe('./');
  await context.setOffline(true); await page.reload();
  await expect(page.getByRole('button', { name: 'Let’s run', exact: false })).toBeEnabled({ timeout: 15000 });
  await page.getByRole('button', { name: 'Let’s run', exact: false }).click();
  await expect(page.locator('.game-stage')).toBeVisible();
  await page.getByRole('button', { name: 'Jump', exact: true }).click();
  await expect(page.locator('.jump-prompt')).toContainText('Aim for the next roof');
  await context.close();
});
test('unsupported graphics produce a useful fallback', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (type: string, ...args: unknown[]) {
      if (type.includes('webgl')) return null;
      return original.apply(this, [type, ...args] as Parameters<typeof original>);
    } as typeof original;
  });
  await page.goto('./');
  await expect(page.getByRole('alert')).toContainText('could not start 3D graphics');
  await expect(page.getByRole('button', { name: 'Reload game' })).toBeVisible();
});
